[dates.historical]
from_date = 2025-01-01
to_date = 2025-12-31

[dates.testing]
from_date = 2026-01-01
to_date = 2026-03-31

[validation.temperature] 
min=-15
max=40

[validation.wind_speed]
min=0
max=75

[validation.radiation]
min=0
max=1100
 